apiVersion: flightctl.thoughtbot.com/v1beta1
kind: Workspace
releases:
  - name: thoughtbot-dot-com-staging
    application: thoughtbot-dot-com
    context: thoughtbot-dot-com-staging
    environment: staging
    manifests:
      path: deploy/staging
  - name: thoughtbot-dot-com-production
    application: thoughtbot-dot-com
    context: thoughtbot-dot-com-production
    environment: production
    manifests:
      path: deploy/production
applications:
  - name: thoughtbot-dot-com
    manifests:
      provider: kustomize
      repo: git@github.com:thoughtbot/thoughtbot.com.git
    provider: kubectl
    params:
      selector:
        app.kubernetes.io/name: thoughtbot-dot-com
      console:
        provider: exec
        params:
          selector:
            app.kubernetes.io/component: console
          container: main
          command:
            - bundle
            - exec
            - rails
            - console
contexts:
  - name: thoughtbot-dot-com-staging
    cluster: thoughtbot-sandbox
    namespace: thoughtbot-dot-com-staging
    auth: thoughtbot-sandbox
  - name: thoughtbot-dot-com-production
    cluster: thoughtbot-production
    namespace: thoughtbot-dot-com-production
    auth: thoughtbot-production
clusters:
  - name: thoughtbot-sandbox
    auth: thoughtbot-sandbox
    provider: eks
    params:
      name: thoughtbot-sandbox-v1
      region: us-east-1
  - name: thoughtbot-production
    auth: thoughtbot-production
    provider: eks
    params:
      name: thoughtbot-production-v1
      region: us-east-1
auth:
  - name: thoughtbot-sandbox
    provider: aws-sso
    params:
      region: us-east-1
      sso_account_id: '181682000713'
      sso_region: us-east-1
      sso_role_name: DeveloperAccess
      sso_start_url: https://thoughtbot.awsapps.com/start
  - name: thoughtbot-production
    provider: aws-sso
    params:
      region: us-east-1
      sso_account_id: '651913466569'
      sso_region: us-east-1
      sso_role_name: DeveloperAccess
      sso_start_url: https://thoughtbot.awsapps.com/start
      