default: &default
  coffee_time:
    active: true
    channel: rotating-coffee-time
    schedule: weekly
    size: 2
  pair_matchmaking:
    active: true
    channel: pair-matchmaking
    schedule: monthly
    size: 2
  rotating_brunch:
    active: false
    channel: rotating-brunch
    schedule: fortnightly
    size: 4
  test_channel:
    active: false
    channel: rotating-test-channel
    schedule: daily
    size: 2

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
